version: '3'
# This docker-compose.yml file is used to build and test quickly
# a specific version of Dolibarr
#
# Before build, define the variable DOLI_VERSION as following:
# $ export DOLI_VERSION=4.0.4
# And then, you can run :
# $ docker-compose up
#
# More informations about Docker-compose : https://docs.docker.com/compose/
networks:
    internal-pod:
        internal: true
    external-pod:
        internal: false

services:
    mariadb:
        image: library/mariadb:latest
        volumes:
            - ./.persist/db:/var/lib/mysql:delegated
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dolibarr
        networks:
            - internal-pod

    web:
        build:
            context: ./docker-compose-links/${DOLI_VERSION}${PHP_VERSION}
        image: tuxgasy/dolibarr:${DOLI_VERSION}${PHP_VERSION}
        volumes:
            - ./.persist/documents:/var/www/documents:delegated
        depends_on:
            - mariadb
        environment:
            DOLI_DB_HOST: mariadb
            DOLI_DB_USER: root
            DOLI_DB_PASSWORD: root
            DOLI_DB_NAME: dolibarr
            DOLI_URL_ROOT: 'http://0.0.0.0'
            WWW_USER_ID: 1000
            WWW_GROUP_ID: 1000
        ports:
            - "80:80"
        networks:
            - internal-pod
            - external-pod

    adminer:
        image: library/adminer:latest
        depends_on:
          - mariadb
        environment:
            ADMINER_DEFAULT_SERVER: mariadb
        ports:
            - 8080:8080
        networks:
            - internal-pod
            - external-pod
